### PR TITLE
Fix GPU PQ build errors and added error checks

### PR DESCRIPTION
**Pull request by bkarsin**
Several fixes to build issues with GPU PQ, including:
- Removed cosine distance code from GPU PQ (not supported with PQ),
- Fixed issue with GPUPQ_Quantizer causing build error,
-  Added checks and error messages for GPU PQ

### CODE REVIEW

**Review by caijiediego — APPROVED** [review]
Fixed GPU build break on both Linux and windows. Tested locally on windows.

**Review by MaggieQi — APPROVED** [review]
approve

**Review by caijiediego — DISMISSED** [review]
Try to trigger GitHub Test

**Review by caijiediego — APPROVED** [review]
Approve

**Pull request merged**
